[package]
name = "fixed_point"
version = "0.1.0"
authors = ["djdis"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
integer-sqrt = "0.1"
